[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 460800

lib_deps =
    bodmer/TFT_eSPI
    greiman/SdFat @ ^2.2.2
    h2zero/NimBLE-Arduino@^1.4.1

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9488_DRIVER=1
    -D TFT_CS=15
    -D TFT_DC=4
    -D TFT_RST=2
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_MISO=19
    -D LOAD_GLCD=1
    -D TOUCH_CS=21
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D SD_CS=5
    -D LOAD_GFXFF=1