#ifndef BLE_UUIDS_H
#define BLE_UUIDS_H

#include <Arduino.h>

struct BleUuidEntry {
  uint16_t id;
  const char* name;
};

// Auto-generated Corporate Member UUIDs (0x16 Service Data)
const BleUuidEntry memberUuids[] PROGMEM = {
  { 0xFC31, "Ford Motor Com." },
  { 0xFC32, "InPlay, Inc." },
  { 0xFC34, "Mitsubishi Ele." },
  { 0xFC35, "Metabowerke Gm." },
  { 0xFC36, "PharmaSens AG" },
  { 0xFC37, "TANlock GmbH" },
  { 0xFC38, "SetPoint Medic." },
  { 0xFC39, "Harman Interna." },
  { 0xFC3A, "C.O.B.O. SpA" },
  { 0xFC3B, "BONX INC." },
  { 0xFC3C, "Eforthink Tech." },
  { 0xFC3D, "Reelables, Inc." },
  { 0xFC3E, "Google LLC" },
  { 0xFC3F, "Milwaukee Elec." },
  { 0xFC41, "Yoto Limited" },
  { 0xFC43, "Atmosic Techno." },
  { 0xFC44, "Block, Inc." },
  { 0xFC45, "Mitsubishi Ele." },
  { 0xFC46, "Xiaomi" },
  { 0xFC47, "Shanghai Ingee." },
  { 0xFC48, "Michelin" },
  { 0xFC49, "Golioth, Inc." },
  { 0xFC4A, "Shenzhen Shokz." },
  { 0xFC4B, "WinMagic Inc." },
  { 0xFC4C, "HP Inc." },
  { 0xFC4D, "Lodestar Techn." },
  { 0xFC4E, "Lodestar Techn." },
  { 0xFC4F, "WaveRF, Corp." },
  { 0xFC50, "Ant Group Co.,." },
  { 0xFC51, "Ant Group Co.,." },
  { 0xFC52, "LG Electronics." },
  { 0xFC53, "LEGIC Identsys." },
  { 0xFC54, "Shenzhen Yinwa." },
  { 0xFC55, "BYD Company Li." },
  { 0xFC56, "Google LLC" },
  { 0xFC57, "Ambient Life I." },
  { 0xFC58, "Shenzhen Minew." },
  { 0xFC59, "Ant Group Co.,." },
  { 0xFC5A, "LAST LOCK INC." },
  { 0xFC5B, "Time Location ." },
  { 0xFC5C, "PLASTIC RESEAR." },
  { 0xFC5D, "GP Acoustics I." },
  { 0xFC5E, "KUBU SMART LIM." },
  { 0xFC5F, "PI-CRYSTAL INC." },
  { 0xFC60, "Ohme Operation." },
  { 0xFC61, "QIKCONNEX LLC" },
  { 0xFC62, "SPRiNTUS GmbH" },
  { 0xFC63, "Volvo Technolo." },
  { 0xFC64, "Volvo Technolo." },
  { 0xFC65, "Robor Electron." },
  { 0xFC66, "Xiaomi Inc." },
  { 0xFC67, "Guangdong Heng." },
  { 0xFC68, "RIGH, INC." },
  { 0xFC69, "Harman Interna." },
  { 0xFC6A, "Sonos Inc" },
  { 0xFC6B, "Sonos Inc" },
  { 0xFC6C, "Powerstick.com" },
  { 0xFC6D, "MOTIVE TECHNOL." },
  { 0xFC6E, "stryker" },
  { 0xFC6F, "NextSense, Inc." },
  { 0xFC70, "MOTIVE TECHNOL." },
  { 0xFC71, "Hive-Zox Inter." },
  { 0xFC72, "iodyne, LLC" },
  { 0xFC73, "Google LLC" },
  { 0xFC74, "EMBEINT INC" },
  { 0xFC75, "Xiaomi Inc." },
  { 0xFC76, "Weber-Stephen ." },
  { 0xFC77, "SING SUN TECHN." },
  { 0xFC78, "DHL" },
  { 0xFC79, "LG Electronics." },
  { 0xFC7A, "Outshiny India." },
  { 0xFC7B, "Testo SE & Co.." },
  { 0xFC7C, "Motorola Mobil." },
  { 0xFC7D, "MML US, Inc" },
  { 0xFC7E, "Harman Interna." },
  { 0xFC7F, "Southco" },
  { 0xFC80, "TELE System Co." },
  { 0xFC81, "Axon Enterpris." },
  { 0xFC82, "Zwift, Inc." },
  { 0xFC83, "iHealth Labs, ." },
  { 0xFC84, "NINGBO FOTILE ." },
  { 0xFC85, "Zhejiang Huanf." },
  { 0xFC86, "Samsara Networ." },
  { 0xFC87, "Samsara Networ." },
  { 0xFC88, "CCC del Uruguay" },
  { 0xFC89, "Intel Corporat." },
  { 0xFC8A, "Intel Corporat." },
  { 0xFC8B, "Kaspersky Lab ." },
  { 0xFC8C, "VusionGroup" },
  { 0xFC8D, "Caire Inc." },
  { 0xFC8E, "Blue Iris Labs." },
  { 0xFC8F, "Bose Corporati." },
  { 0xFC90, "Wiliot LTD." },
  { 0xFC91, "Samsung Electr." },
  { 0xFC92, "Furuno Electri." },
  { 0xFC93, "Komatsu Ltd." },
  { 0xFC94, "Apple Inc." },
  { 0xFC95, "Hippo Camp Sof." },
  { 0xFC96, "LEGO System A/S" },
  { 0xFC97, "Japan Display ." },
  { 0xFC98, "Ruuvi Innovati." },
  { 0xFC99, "Badger Meter" },
  { 0xFC9A, "Koppli AB" },
  { 0xFC9B, "Merry Electron." },
  { 0xFC9D, "Lenovo (Singap." },
  { 0xFC9E, "Dell Computer ." },
  { 0xFC9F, "Delta Developm." },
  { 0xFCA0, "Apple Inc." },
  { 0xFCA1, "PF SCHWEISSTEC." },
  { 0xFCA2, "Meizu Technolo." },
  { 0xFCA3, "Gunnebo Aktieb." },
  { 0xFCA4, "HP Inc." },
  { 0xFCA5, "HAYWARD INDUST." },
  { 0xFCA6, "Hubble Network." },
  { 0xFCA7, "Hubble Network." },
  { 0xFCA8, "Medtronic Inc." },
  { 0xFCA9, "Medtronic Inc." },
  { 0xFCAA, "Spintly, Inc." },
  { 0xFCAB, "IRISS INC." },
  { 0xFCAC, "IRISS INC." },
  { 0xFCAD, "Beijing 99help." },
  { 0xFCAE, "Imagine Market." },
  { 0xFCAF, "AltoBeam Inc." },
  { 0xFCB0, "Ford Motor Com." },
  { 0xFCB1, "Google LLC" },
  { 0xFCB2, "Apple Inc." },
  { 0xFCB3, "SWEEN" },
  { 0xFCB4, "OMRON HEALTHCA." },
  { 0xFCB5, "OMRON HEALTHCA." },
  { 0xFCB6, "OMRON HEALTHCA." },
  { 0xFCB7, "T-Mobile USA" },
  { 0xFCB8, "Ribbiot, INC." },
  { 0xFCB9, "Lumi United Te." },
  { 0xFCBA, "BlueID GmbH" },
  { 0xFCBB, "SharkNinja Ope." },
  { 0xFCBC, "Drowsy Digital." },
  { 0xFCBD, "Toshiba Corpor." },
  { 0xFCBE, "Musen Connect,." },
  { 0xFCBF, "ASSA ABLOY Ope." },
  { 0xFCC0, "Xiaomi Inc." },
  { 0xFCC1, "TIMECODE SYSTE." },
  { 0xFCC2, "Qualcomm Techn." },
  { 0xFCC3, "HP Inc." },
  { 0xFCC4, "OMRON(DALIAN) ." },
  { 0xFCC5, "OMRON(DALIAN) ." },
  { 0xFCC6, "Wiliot LTD." },
  { 0xFCC7, "PB INC." },
  { 0xFCC8, "Allthenticate,." },
  { 0xFCC9, "SkyHawke Techn." },
  { 0xFCCA, "Cosmed s.r.l." },
  { 0xFCCB, "TOTO LTD." },
  { 0xFCCD, "Marshall Group." },
  { 0xFCCE, "Luna Health, I." },
  { 0xFCCF, "Google LLC" },
  { 0xFCD0, "Laerdal Medica." },
  { 0xFCD1, "Shenzhen Benwe." },
  { 0xFCD2, "Allterco Robot." },
  { 0xFCD3, "Fisher & Payke." },
  { 0xFCD4, "OMRON HEALTHCA." },
  { 0xFCD5, "Nortek Securit." },
  { 0xFCD6, "SWISSINNO SOLU." },
  { 0xFCD7, "PowerPal Pty L." },
  { 0xFCD8, "Appex Factory ." },
  { 0xFCD9, "Huso, INC" },
  { 0xFCDA, "Draeger" },
  { 0xFCDB, "aconno GmbH" },
  { 0xFCDC, "Amazon.com Ser." },
  { 0xFCDD, "Mobilaris AB" },
  { 0xFCDE, "ARCTOP, INC." },
  { 0xFCDF, "NIO USA, Inc." },
  { 0xFCE0, "Akciju sabiedr." },
  { 0xFCE1, "Sony Group Cor." },
  { 0xFCE2, "Baracoda Daily." },
  { 0xFCE3, "Smith & Nephew." },
  { 0xFCE4, "Samsara Networ." },
  { 0xFCE5, "Samsara Networ." },
  { 0xFCE6, "Guard RFID Sol." },
  { 0xFCE7, "TKH Security B." },
  { 0xFCE8, "ITT Industries" },
  { 0xFCE9, "MindRhythm, In." },
  { 0xFCEA, "Chess Wise B.V." },
  { 0xFCEB, "Avi-On" },
  { 0xFCEC, "Griffwerk GmbH" },
  { 0xFCED, "Workaround Gmbh" },
  { 0xFCEE, "Velentium, LLC" },
  { 0xFCEF, "Divesoft s.r.o." },
  { 0xFCF0, "Security Enhan." },
  { 0xFCF1, "Google LLC" },
  { 0xFCF2, "Bitwards Oy" },
  { 0xFCF3, "Armatura LLC" },
  { 0xFCF4, "Allegion" },
  { 0xFCF5, "Trident Commun." },
  { 0xFCF6, "The Linux Foun." },
  { 0xFCF7, "Honor Device C." },
  { 0xFCF8, "Honor Device C." },
  { 0xFCF9, "Leupold & Stev." },
  { 0xFCFA, "Leupold & Stev." },
  { 0xFCFB, "Shenzhen Benwe." },
  { 0xFCFC, "Barrot Technol." },
  { 0xFCFD, "Barrot Technol." },
  { 0xFCFE, "Sonova Consume." },
  { 0xFCFF, "701x" },
  { 0xFD00, "FUTEK Advanced." },
  { 0xFD01, "Sanvita Medica." },
  { 0xFD02, "LEGO System A/S" },
  { 0xFD03, "Quuppa Oy" },
  { 0xFD04, "Shure Inc." },
  { 0xFD05, "Qualcomm Techn." },
  { 0xFD06, "RACE-AI LLC" },
  { 0xFD07, "Swedlock AB" },
  { 0xFD08, "Bull Group Inc." },
  { 0xFD09, "Cousins and Se." },
  { 0xFD0A, "Luminostics, I." },
  { 0xFD0B, "Luminostics, I." },
  { 0xFD0C, "OSM HK Limited" },
  { 0xFD0D, "Blecon Ltd" },
  { 0xFD0E, "HerdDogg, Inc" },
  { 0xFD0F, "AEON MOTOR CO.." },
  { 0xFD10, "AEON MOTOR CO.." },
  { 0xFD11, "AEON MOTOR CO.." },
  { 0xFD12, "AEON MOTOR CO.." },
  { 0xFD13, "BRG Sports, In." },
  { 0xFD14, "BRG Sports, In." },
  { 0xFD15, "Panasonic Corp." },
  { 0xFD16, "Sensitech, Inc." },
  { 0xFD17, "LEGIC Identsys." },
  { 0xFD18, "LEGIC Identsys." },
  { 0xFD19, "Smith & Nephew." },
  { 0xFD1A, "CSIRO" },
  { 0xFD1B, "Helios Sports,." },
  { 0xFD1C, "Brady Worldwid." },
  { 0xFD1D, "Samsung Electr." },
  { 0xFD1E, "Plume Design I." },
  { 0xFD1F, "3M" },
  { 0xFD20, "GN Hearing A/S" },
  { 0xFD21, "Huawei Technol." },
  { 0xFD22, "Huawei Technol." },
  { 0xFD23, "DOM Sicherheit." },
  { 0xFD24, "GD Midea Air-C." },
  { 0xFD25, "GD Midea Air-C." },
  { 0xFD26, "Novo Nordisk A." },
  { 0xFD27, "Integrated Ill." },
  { 0xFD28, "Julius Blum Gm." },
  { 0xFD29, "Asahi Kasei Co." },
  { 0xFD2A, "Sony Corporati." },
  { 0xFD2B, "The Access Tec." },
  { 0xFD2C, "The Access Tec." },
  { 0xFD2D, "Xiaomi Inc." },
  { 0xFD2E, "Bitstrata Syst." },
  { 0xFD2F, "Bitstrata Syst." },
  { 0xFD30, "Sesam Solution." },
  { 0xFD31, "LG Electronics." },
  { 0xFD32, "Gemalto Holdin." },
  { 0xFD33, "DashLogic, Inc." },
  { 0xFD34, "Aerosens LLC." },
  { 0xFD35, "Transsion Hold." },
  { 0xFD36, "Google LLC" },
  { 0xFD37, "TireCheck GmbH" },
  { 0xFD38, "Danfoss A/S" },
  { 0xFD39, "PREDIKTAS" },
  { 0xFD3A, "Verkada Inc." },
  { 0xFD3B, "Verkada Inc." },
  { 0xFD3C, "Redline Commun." },
  { 0xFD3D, "Woan Technolog." },
  { 0xFD3E, "Pure Watercraf." },
  { 0xFD3F, "Cognosos, Inc" },
  { 0xFD40, "Beflex Inc." },
  { 0xFD41, "Amazon Lab126" },
  { 0xFD42, "Globe (Jiangsu." },
  { 0xFD43, "Apple Inc." },
  { 0xFD44, "Apple Inc." },
  { 0xFD45, "GB Solution co." },
  { 0xFD46, "Lemco IKE" },
  { 0xFD47, "Liberty Global." },
  { 0xFD48, "Geberit Intern." },
  { 0xFD49, "Panasonic Corp." },
  { 0xFD4A, "Sigma Elektro ." },
  { 0xFD4B, "Samsung Electr." },
  { 0xFD4C, "Adolf Wuerth G." },
  { 0xFD4D, "70mai Co.,Ltd." },
  { 0xFD4E, "70mai Co.,Ltd." },
  { 0xFD4F, "SONITOR TECHNO." },
  { 0xFD50, "Hangzhou Tuya ." },
  { 0xFD51, "UTC Fire and S." },
  { 0xFD52, "UTC Fire and S." },
  { 0xFD53, "PCI Private Li." },
  { 0xFD54, "Qingdao Haier ." },
  { 0xFD55, "Braveheart Wir." },
  { 0xFD56, "Resmed Ltd" },
  { 0xFD57, "Volvo Car Corp." },
  { 0xFD58, "Volvo Car Corp." },
  { 0xFD59, "Samsung Electr." },
  { 0xFD5A, "Samsung Electr." },
  { 0xFD5B, "V2SOFT INC." },
  { 0xFD5C, "React Mobile" },
  { 0xFD5D, "maxon motor lt." },
  { 0xFD5E, "Tapkey GmbH" },
  { 0xFD5F, "Meta Platforms." },
  { 0xFD60, "Sercomm Corpor." },
  { 0xFD61, "Arendi AG" },
  { 0xFD62, "Google LLC" },
  { 0xFD63, "Google LLC" },
  { 0xFD64, "INRIA" },
  { 0xFD65, "Razer Inc." },
  { 0xFD66, "Zebra Technolo." },
  { 0xFD67, "Montblanc Simp." },
  { 0xFD68, "Ubique Innovat." },
  { 0xFD69, "Samsung Electr." },
  { 0xFD6A, "Emerson" },
  { 0xFD6B, "rapitag GmbH" },
  { 0xFD6C, "Samsung Electr." },
  { 0xFD6D, "Sigma Elektro ." },
  { 0xFD6E, "Polidea sp. z ." },
  { 0xFD6F, "Apple, Inc." },
  { 0xFD70, "GuangDong Oppo." },
  { 0xFD71, "GN Hearing A/S" },
  { 0xFD72, "Logitech Inter." },
  { 0xFD73, "BRControls Pro." },
  { 0xFD74, "BRControls Pro." },
  { 0xFD75, "Insulet Corpor." },
  { 0xFD76, "Insulet Corpor." },
  { 0xFD77, "Withings" },
  { 0xFD78, "Withings" },
  { 0xFD79, "Withings" },
  { 0xFD7A, "Withings" },
  { 0xFD7B, "WYZE LABS, INC." },
  { 0xFD7C, "Toshiba Inform." },
  { 0xFD7D, "Center for Adv." },
  { 0xFD7E, "Samsung Electr." },
  { 0xFD7F, "Husqvarna AB" },
  { 0xFD80, "Phindex Techno." },
  { 0xFD81, "CANDY HOUSE, I." },
  { 0xFD82, "Sony Corporati." },
  { 0xFD83, "iNFORM Technol." },
  { 0xFD84, "Tile, Inc." },
  { 0xFD85, "Husqvarna AB" },
  { 0xFD86, "Abbott" },
  { 0xFD87, "Google LLC" },
  { 0xFD88, "Urbanminded LTD" },
  { 0xFD89, "Urbanminded LTD" },
  { 0xFD8A, "Signify Nether." },
  { 0xFD8B, "Jigowatts Inc." },
  { 0xFD8C, "Google LLC" },
  { 0xFD8D, "quip NYC Inc." },
  { 0xFD8E, "Motorola Solut." },
  { 0xFD90, "Guangzhou Supe." },
  { 0xFD91, "Groove X, Inc." },
  { 0xFD92, "Qualcomm Techn." },
  { 0xFD93, "Bayerische Mot." },
  { 0xFD94, "Hewlett Packar." },
  { 0xFD95, "Rigado" },
  { 0xFD96, "Google LLC" },
  { 0xFD97, "June Life, Inc." },
  { 0xFD98, "Disney Worldwi." },
  { 0xFD99, "ABB Oy" },
  { 0xFD9A, "Huawei Technol." },
  { 0xFD9B, "Huawei Technol." },
  { 0xFD9C, "Huawei Technol." },
  { 0xFD9D, "Gastec Corpora." },
  { 0xFD9E, "The Coca-Cola ." },
  { 0xFD9F, "VitalTech Affi." },
  { 0xFDA0, "Secugen Corpor." },
  { 0xFDA1, "Groove X, Inc" },
  { 0xFDA2, "Groove X, Inc" },
  { 0xFDA3, "Inseego Corp." },
  { 0xFDA4, "Inseego Corp." },
  { 0xFDA5, "Neurostim OAB,." },
  { 0xFDA6, "WWZN Informati." },
  { 0xFDA7, "WWZN Informati." },
  { 0xFDA8, "PSA Peugeot Ci." },
  { 0xFDA9, "Rhombus System." },
  { 0xFDAA, "Xiaomi Inc." },
  { 0xFDAB, "Xiaomi Inc." },
  { 0xFDAC, "Tentacle Sync ." },
  { 0xFDAD, "Houwa System D." },
  { 0xFDAE, "Houwa System D." },
  { 0xFDAF, "Wiliot LTD" },
  { 0xFDB0, "Oura Health Ltd" },
  { 0xFDB1, "Oura Health Ltd" },
  { 0xFDB2, "Portable Multi." },
  { 0xFDB3, "Audiodo AB" },
  { 0xFDB4, "HP Inc" },
  { 0xFDB5, "ECSG" },
  { 0xFDB6, "GWA Hygiene Gm." },
  { 0xFDB7, "LivaNova USA I." },
  { 0xFDB8, "LivaNova USA I." },
  { 0xFDBB, "Profoto" },
  { 0xFDBC, "Emerson" },
  { 0xFDBD, "Clover Network." },
  { 0xFDBE, "California Thi." },
  { 0xFDBF, "California Thi." },
  { 0xFDC0, "Hunter Douglas" },
  { 0xFDC1, "Hunter Douglas" },
  { 0xFDC2, "Baidu Online N." },
  { 0xFDC3, "Baidu Online N." },
  { 0xFDC4, "Simavita (Aust." },
  { 0xFDC5, "Automatic Labs" },
  { 0xFDC6, "Eli Lilly and ." },
  { 0xFDC7, "Eli Lilly and ." },
  { 0xFDC8, "Hach – Danaher" },
  { 0xFDC9, "Busch-Jaeger E." },
  { 0xFDCA, "Fortin Electro." },
  { 0xFDCB, "Meggitt SA" },
  { 0xFDCC, "Shoof Technolo." },
  { 0xFDCD, "Qingping Techn." },
  { 0xFDCE, "SENNHEISER ele." },
  { 0xFDCF, "Nalu Medical, ." },
  { 0xFDD0, "Huawei Technol." },
  { 0xFDD1, "Huawei Technol." },
  { 0xFDD2, "Bose Corporati." },
  { 0xFDD3, "FUBA Automotiv." },
  { 0xFDD4, "LX Solutions P." },
  { 0xFDD5, "Brompton Bicyc." },
  { 0xFDD6, "Ministry of Su." },
  { 0xFDD7, "Copeland Cold ." },
  { 0xFDD8, "Jiangsu Terano." },
  { 0xFDD9, "Jiangsu Terano." },
  { 0xFDDA, "MHCS" },
  { 0xFDDB, "Samsung Electr." },
  { 0xFDDC, "4iiii Innovati." },
  { 0xFDDD, "Arch Systems I." },
  { 0xFDDE, "Noodle Technol." },
  { 0xFDDF, "Harman Interna." },
  { 0xFDE0, "John Deere" },
  { 0xFDE1, "Fortin Electro." },
  { 0xFDE2, "Google LLC" },
  { 0xFDE3, "Abbott Diabete." },
  { 0xFDE4, "JUUL Labs, Inc." },
  { 0xFDE5, "SMK Corporation" },
  { 0xFDE6, "Intelletto Tec." },
  { 0xFDE7, "SECOM Co., LTD" },
  { 0xFDE8, "Robert Bosch G." },
  { 0xFDE9, "Spacesaver Cor." },
  { 0xFDEA, "SeeScan, Inc" },
  { 0xFDEB, "Syntronix Corp." },
  { 0xFDEC, "Mannkind Corpo." },
  { 0xFDED, "Pole Star" },
  { 0xFDEE, "Huawei Technol." },
  { 0xFDEF, "ART AND PROGRA." },
  { 0xFDF0, "Google LLC" },
  { 0xFDF1, "LAMPLIGHT Co.,." },
  { 0xFDF2, "AMICCOM Electr." },
  { 0xFDF3, "Amersports" },
  { 0xFDF4, "O. E. M. Contr." },
  { 0xFDF5, "Milwaukee Elec." },
  { 0xFDF6, "AIAIAI ApS" },
  { 0xFDF7, "HP Inc." },
  { 0xFDF8, "Onvocal" },
  { 0xFDF9, "INIA" },
  { 0xFDFA, "Tandem Diabete." },
  { 0xFDFB, "Tandem Diabete." },
  { 0xFDFC, "Optrel AG" },
  { 0xFDFD, "RecursiveSoft ." },
  { 0xFDFE, "ADHERIUM(NZ) L." },
  { 0xFDFF, "OSRAM GmbH" },
  { 0xFE00, "Amazon.com Ser." },
  { 0xFE01, "Duracell U.S. ." },
  { 0xFE02, "Robert Bosch G." },
  { 0xFE03, "Amazon.com Ser." },
  { 0xFE04, "Motorola Solut." },
  { 0xFE05, "CORE Transport." },
  { 0xFE06, "Qualcomm Techn." },
  { 0xFE07, "Sonos, Inc." },
  { 0xFE08, "Microsoft" },
  { 0xFE09, "Pillsy, Inc." },
  { 0xFE0A, "ruwido austria." },
  { 0xFE0B, "ruwido austria." },
  { 0xFE0C, "Procter & Gamb." },
  { 0xFE0D, "Procter & Gamb." },
  { 0xFE0E, "Setec Pty Ltd" },
  { 0xFE0F, "Signify Nether." },
  { 0xFE10, "LAPIS Technolo." },
  { 0xFE11, "GMC-I Messtech." },
  { 0xFE12, "M-Way Solution." },
  { 0xFE13, "Apple Inc." },
  { 0xFE14, "Flextronics In." },
  { 0xFE15, "Amazon.com Ser." },
  { 0xFE16, "Footmarks, Inc." },
  { 0xFE17, "Telit Wireless." },
  { 0xFE18, "Runtime, Inc." },
  { 0xFE19, "Google LLC" },
  { 0xFE1A, "Tyto Life LLC" },
  { 0xFE1B, "Tyto Life LLC" },
  { 0xFE1C, "NetMedia, Inc." },
  { 0xFE1D, "Illuminati Ins." },
  { 0xFE1E, "LAMPLIGHT Co.,." },
  { 0xFE1F, "Garmin Interna." },
  { 0xFE20, "Emerson" },
  { 0xFE21, "Bose Corporati." },
  { 0xFE22, "Zoll Medical C." },
  { 0xFE23, "Zoll Medical C." },
  { 0xFE24, "August Home Inc" },
  { 0xFE25, "Apple, Inc." },
  { 0xFE26, "Google LLC" },
  { 0xFE27, "Google LLC" },
  { 0xFE28, "Ayla Networks" },
  { 0xFE29, "Gibson Innovat." },
  { 0xFE2A, "DaisyWorks, In." },
  { 0xFE2B, "ITT Industries" },
  { 0xFE2C, "Google LLC" },
  { 0xFE2D, "LAMPLIGHT Co.,." },
  { 0xFE2E, "ERi,Inc." },
  { 0xFE2F, "CRESCO Wireles." },
  { 0xFE30, "Volkswagen AG" },
  { 0xFE31, "Volkswagen AG" },
  { 0xFE32, "Pro-Mark, Inc." },
  { 0xFE33, "CHIPOLO d.o.o." },
  { 0xFE34, "SmallLoop LLC" },
  { 0xFE35, "HUAWEI Technol." },
  { 0xFE36, "HUAWEI Technol." },
  { 0xFE39, "TTS Tooltechni." },
  { 0xFE3A, "TTS Tooltechni." },
  { 0xFE3B, "Dolby Laborato." },
  { 0xFE3C, "alibaba" },
  { 0xFE3D, "BD Medical" },
  { 0xFE3E, "BD Medical" },
  { 0xFE3F, "Friday Labs Li." },
  { 0xFE40, "Inugo Systems ." },
  { 0xFE41, "Inugo Systems ." },
  { 0xFE42, "Nets A/S" },
  { 0xFE43, "Andreas Stihl ." },
  { 0xFE44, "SK Telecom" },
  { 0xFE45, "Snapchat Inc" },
  { 0xFE46, "B&O Play A/S" },
  { 0xFE47, "General Motors" },
  { 0xFE48, "General Motors" },
  { 0xFE49, "SenionLab AB" },
  { 0xFE4A, "OMRON HEALTHCA." },
  { 0xFE4B, "Signify Nether." },
  { 0xFE4C, "Volkswagen AG" },
  { 0xFE4D, "Casambi Techno." },
  { 0xFE4E, "NTT docomo" },
  { 0xFE4F, "Molekule, Inc." },
  { 0xFE50, "Google LLC" },
  { 0xFE51, "SRAM" },
  { 0xFE52, "SetPoint Medic." },
  { 0xFE53, "3M" },
  { 0xFE54, "Motiv, Inc." },
  { 0xFE55, "Google LLC" },
  { 0xFE56, "Google LLC" },
  { 0xFE57, "Dotted Labs" },
  { 0xFE58, "Nordic Semicon." },
  { 0xFE59, "Nordic Semicon." },
  { 0xFE5A, "Cronologics Co." },
  { 0xFE5B, "GT-tronics HK ." },
  { 0xFE5C, "million hunter." },
  { 0xFE5D, "Grundfos A/S" },
  { 0xFE5E, "Plastc Corpora." },
  { 0xFE5F, "Eyefi, Inc." },
  { 0xFE60, "Lierda Science." },
  { 0xFE61, "Logitech Inter." },
  { 0xFE62, "Indagem Tech L." },
  { 0xFE63, "Connected Yard." },
  { 0xFE64, "Siemens AG" },
  { 0xFE65, "CHIPOLO d.o.o." },
  { 0xFE66, "Intel Corporat." },
  { 0xFE67, "Lab Sensor Sol." },
  { 0xFE68, "Capsle Technol." },
  { 0xFE69, "Capsle Technol." },
  { 0xFE6A, "Kontakt Micro-." },
  { 0xFE6B, "TASER Internat." },
  { 0xFE6C, "TASER Internat." },
  { 0xFE6D, "The University." },
  { 0xFE6E, "The University." },
  { 0xFE6F, "LINE Corporati." },
  { 0xFE70, "Beijing Jingdo." },
  { 0xFE71, "Plume Design I." },
  { 0xFE72, "Abbott (former." },
  { 0xFE73, "Abbott (former." },
  { 0xFE74, "unwire" },
  { 0xFE75, "TangoMe" },
  { 0xFE76, "TangoMe" },
  { 0xFE77, "Hewlett-Packar." },
  { 0xFE78, "Hewlett-Packar." },
  { 0xFE79, "Zebra Technolo." },
  { 0xFE7A, "Bragi GmbH" },
  { 0xFE7B, "Orion Labs, In." },
  { 0xFE7C, "Telit Wireless." },
  { 0xFE7D, "Aterica Health." },
  { 0xFE7E, "Awear Solution." },
  { 0xFE7F, "Doppler Lab" },
  { 0xFE80, "Doppler Lab" },
  { 0xFE81, "Medtronic Inc." },
  { 0xFE82, "Medtronic Inc." },
  { 0xFE83, "Blue Bite" },
  { 0xFE84, "RF Digital Corp" },
  { 0xFE85, "RF Digital Corp" },
  { 0xFE86, "HUAWEI Technol." },
  { 0xFE87, "Qingdao Yeelin." },
  { 0xFE88, "SALTO SYSTEMS ." },
  { 0xFE89, "B&O Play A/S" },
  { 0xFE8A, "Apple, Inc." },
  { 0xFE8B, "Apple, Inc." },
  { 0xFE8C, "TRON Forum" },
  { 0xFE8D, "Interaxon Inc." },
  { 0xFE8E, "ARM Ltd" },
  { 0xFE8F, "CSR" },
  { 0xFE90, "JUMA" },
  { 0xFE91, "Shanghai Imila." },
  { 0xFE92, "Jarden Safety ." },
  { 0xFE93, "OttoQ In" },
  { 0xFE94, "OttoQ In" },
  { 0xFE95, "Xiaomi Inc." },
  { 0xFE96, "Tesla Motors I." },
  { 0xFE97, "Tesla Motors I." },
  { 0xFE98, "Currant Inc" },
  { 0xFE99, "Currant Inc" },
  { 0xFE9A, "Estimote" },
  { 0xFE9B, "Samsara Networ." },
  { 0xFE9C, "GSI Laboratori." },
  { 0xFE9D, "Mobiquity Netw." },
  { 0xFE9E, "Renesas Design." },
  { 0xFE9F, "Google LLC" },
  { 0xFEA0, "Google LLC" },
  { 0xFEA3, "ITT Industries" },
  { 0xFEA4, "Paxton Access ." },
  { 0xFEA5, "GoPro, Inc." },
  { 0xFEA6, "GoPro, Inc." },
  { 0xFEA7, "UTC Fire and S." },
  { 0xFEA8, "Savant Systems." },
  { 0xFEA9, "Savant Systems." },
  { 0xFEAA, "Google LLC" },
  { 0xFEAB, "Nokia" },
  { 0xFEAC, "Nokia" },
  { 0xFEAD, "Nokia" },
  { 0xFEAE, "Nokia" },
  { 0xFEAF, "Nest Labs Inc" },
  { 0xFEB0, "Nest Labs Inc" },
  { 0xFEB1, "Electronics To." },
  { 0xFEB2, "Microsoft Corp." },
  { 0xFEB3, "Taobao" },
  { 0xFEB4, "WiSilica Inc." },
  { 0xFEB5, "WiSilica Inc." },
  { 0xFEB6, "Vencer Co., Ltd" },
  { 0xFEB7, "Meta Platforms." },
  { 0xFEB8, "Meta Platforms." },
  { 0xFEB9, "LG Electronics" },
  { 0xFEBA, "Tencent Holdin." },
  { 0xFEBB, "adafruit indus." },
  { 0xFEBC, "Dexcom Inc" },
  { 0xFEBD, "Clover Network." },
  { 0xFEBE, "Bose Corporati." },
  { 0xFEBF, "Nod, Inc." },
  { 0xFEC0, "KDDI Corporati." },
  { 0xFEC1, "KDDI Corporati." },
  { 0xFEC2, "Blue Spark Tec." },
  { 0xFEC3, "360fly, Inc." },
  { 0xFEC4, "PLUS Location ." },
  { 0xFEC5, "Realtek Semico." },
  { 0xFEC6, "Kocomojo, LLC" },
  { 0xFEC7, "Apple, Inc." },
  { 0xFEC8, "Apple, Inc." },
  { 0xFEC9, "Apple, Inc." },
  { 0xFECA, "Apple, Inc." },
  { 0xFECB, "Apple, Inc." },
  { 0xFECC, "Apple, Inc." },
  { 0xFECD, "Apple, Inc." },
  { 0xFECE, "Apple, Inc." },
  { 0xFECF, "Apple, Inc." },
  { 0xFED0, "Apple, Inc." },
  { 0xFED1, "Apple, Inc." },
  { 0xFED2, "Apple, Inc." },
  { 0xFED3, "Apple, Inc." },
  { 0xFED4, "Apple, Inc." },
  { 0xFED5, "Plantronics In." },
  { 0xFED6, "Broadcom" },
  { 0xFED7, "Broadcom" },
  { 0xFED8, "Google LLC" },
  { 0xFED9, "Pebble Technol." },
  { 0xFEDA, "ISSC Technolog." },
  { 0xFEDB, "Perka, Inc." },
  { 0xFEDC, "Jawbone" },
  { 0xFEDD, "Jawbone" },
  { 0xFEDE, "Coin, Inc." },
  { 0xFEE0, "Anhui Huami In." },
  { 0xFEE1, "Anhui Huami In." },
  { 0xFEE2, "Anki, Inc." },
  { 0xFEE3, "Anki, Inc." },
  { 0xFEE4, "Nordic Semicon." },
  { 0xFEE5, "Nordic Semicon." },
  { 0xFEE6, "Silvair, Inc." },
  { 0xFEE7, "Tencent Holdin." },
  { 0xFEE8, "Quintic Corp." },
  { 0xFEE9, "Quintic Corp." },
  { 0xFEEA, "Swirl Networks." },
  { 0xFEEB, "Swirl Networks." },
  { 0xFEEC, "Tile, Inc." },
  { 0xFEED, "Tile, Inc." },
  { 0xFEEE, "Polar Electro ." },
  { 0xFEEF, "Polar Electro ." },
  { 0xFEF0, "Intel" },
  { 0xFEF1, "CSR" },
  { 0xFEF2, "CSR" },
  { 0xFEF3, "Google LLC" },
  { 0xFEF4, "Google LLC" },
  { 0xFEF5, "Dialog Semicon." },
  { 0xFEF6, "Wicentric, Inc." },
  { 0xFEF7, "Aplix Corporat." },
  { 0xFEF8, "Aplix Corporat." },
  { 0xFEF9, "PayPal, Inc." },
  { 0xFEFA, "PayPal, Inc." },
  { 0xFEFB, "Telit Wireless." },
  { 0xFEFC, "Gimbal, Inc." },
  { 0xFEFD, "Gimbal, Inc." },
  { 0xFEFE, "GN Hearing A/S" },
  { 0xFEFF, "GN Netcom" },
};
const int numMemberUuids = 706;

// Auto-generated Standard Service UUIDs (0x02/0x03)
const BleUuidEntry serviceUuids[] PROGMEM = {
  { 0x1800, "GAP" },
  { 0x1801, "GATT" },
  { 0x1802, "Immediate Alert" },
  { 0x1803, "Link Loss" },
  { 0x1804, "Tx Power" },
  { 0x1805, "Current Time" },
  { 0x1806, "Reference Time." },
  { 0x1807, "Next DST Change" },
  { 0x1808, "Glucose" },
  { 0x1809, "Health Thermom." },
  { 0x180A, "Device Informa." },
  { 0x180D, "Heart Rate" },
  { 0x180E, "Phone Alert St." },
  { 0x180F, "Battery" },
  { 0x1810, "Blood Pressure" },
  { 0x1811, "Alert Notifica." },
  { 0x1812, "Human Interfac." },
  { 0x1813, "Scan Parameters" },
  { 0x1814, "Running Speed ." },
  { 0x1815, "Automation IO" },
  { 0x1816, "Cycling Speed ." },
  { 0x1818, "Cycling Power" },
  { 0x1819, "Location and N." },
  { 0x181A, "Environmental ." },
  { 0x181B, "Body Compositi." },
  { 0x181C, "User Data" },
  { 0x181D, "Weight Scale" },
  { 0x181E, "Bond Management" },
  { 0x181F, "Continuous Glu." },
  { 0x1820, "Internet Proto." },
  { 0x1821, "Indoor Positio." },
  { 0x1822, "Pulse Oximeter" },
  { 0x1823, "HTTP Proxy" },
  { 0x1824, "Transport Disc." },
  { 0x1825, "Object Transfer" },
  { 0x1826, "Fitness Machine" },
  { 0x1827, "Mesh Provision." },
  { 0x1828, "Mesh Proxy" },
  { 0x1829, "Reconnection C." },
  { 0x183A, "Insulin Delive." },
  { 0x183B, "Binary Sensor" },
  { 0x183C, "Emergency Conf." },
  { 0x183D, "Authorization ." },
  { 0x183E, "Physical Activ." },
  { 0x183F, "Elapsed Time" },
  { 0x1840, "Generic Health." },
  { 0x1843, "Audio Input Co." },
  { 0x1844, "Volume Control" },
  { 0x1845, "Volume Offset ." },
  { 0x1846, "Coordinated Se." },
  { 0x1847, "Device Time" },
  { 0x1848, "Media Control" },
  { 0x1849, "Generic Media ." },
  { 0x184A, "Constant Tone ." },
  { 0x184B, "Telephone Bear." },
  { 0x184C, "Generic Teleph." },
  { 0x184D, "Microphone Con." },
  { 0x184E, "Audio Stream C." },
  { 0x184F, "Broadcast Audi." },
  { 0x1850, "Published Audi." },
  { 0x1851, "Basic Audio An." },
  { 0x1852, "Broadcast Audi." },
  { 0x1853, "Common Audio" },
  { 0x1854, "Hearing Access" },
  { 0x1855, "Telephony and ." },
  { 0x1856, "Public Broadca." },
  { 0x1857, "Electronic She." },
  { 0x1858, "Gaming Audio" },
  { 0x1859, "Mesh Proxy Sol." },
  { 0x185A, "Industrial Mea." },
  { 0x185B, "Ranging" },
  { 0x185C, "HID ISO" },
  { 0x185D, "Cookware" },
  { 0x185E, "Voice Assistant" },
  { 0x185F, "Generic Voice ." },
};
const int numServiceUuids = 75;

#endif // BLE_UUIDS_H
